import '../styles/main.scss';
import {DropdownCollection} from "./Dropdown.js";
import {SearchCollection} from "./Search.js";
import {BurgerButton} from "./BurgerButton";
import {SubscribeFormCollection} from "./SubscribeForm.js";
import {PopupCollection} from "./Popup.js";
import {SliderCollection} from "./Slider.js";
import {ProductsCollection} from "./Products.js";
import {CartCollection} from "./Cart.js";
import {GalleryCollection} from "./Gallery.js";
import {GalleryScrollCollection} from "./GalleryScroll.js";

new DropdownCollection();
new SearchCollection();
new BurgerButton();
new SubscribeFormCollection();
new PopupCollection();
new SliderCollection();
new ProductsCollection();
new CartCollection();
new GalleryCollection();
new GalleryScrollCollection();
